(function(){
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const viewerHref=s=>'#simulation='+encodeURIComponent(s.id);
const catalog=document.getElementById('catalog');
const topics=document.getElementById('topics');
let active='all';
const ordered=SIMS; // Display order is the order in simulations.js.
document.getElementById('total').textContent=SIMS.length;
topics.innerHTML=[{id:'all',nav:'All simulations'},...GROUPS].map(g=>`<button type="button" data-topic="${esc(g.id)}" aria-pressed="${g.id==='all'}">${esc(g.nav)}<span>${g.id==='all'?SIMS.length:SIMS.filter(s=>s.group===g.id).length}</span></button>`).join('');
document.getElementById('cards').innerHTML=ordered.map(sim=>`<article class="card" id="sim-${esc(sim.id)}" data-id="${esc(sim.id)}" data-group="${esc(sim.group)}"><a class="thumb" href="${viewerHref(sim)}" aria-label="Open ${esc(sim.title)}"><span class="preview-label">Animated preview</span><div class="stage"><canvas data-sim="${esc(sim.id)}" aria-label="Animated illustration: ${esc(sim.title)}"></canvas></div></a><div class="card-content"><p class="category">${esc(GROUPS.find(g=>g.id===sim.group)?.title||sim.group)}</p><h3><a href="${viewerHref(sim)}">${esc(sim.title)}</a></h3><p class="hook">${esc(sim.hook)}</p><details><summary>What you can explore</summary><p>${esc(sim.detail)}</p></details><a class="launch" href="${viewerHref(sim)}">Open simulation <span aria-hidden="true">↗</span></a></div></article>`).join('');
const search=document.getElementById('search');
function filter(){const query=search.value.trim().toLowerCase();let count=0;for(const sim of SIMS){const show=(active==='all'||sim.group===active)&&[sim.title,sim.hook,sim.detail,GROUPS.find(g=>g.id===sim.group)?.title].join(' ').toLowerCase().includes(query);document.getElementById('sim-'+sim.id).hidden=!show;if(show)count++;}topics.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',b.dataset.topic===active));document.getElementById('result-count').textContent=count+' of '+SIMS.length+' simulations';document.getElementById('empty').hidden=count!==0;
// Position-aware spans also keep filtered result rows complete.
const visible=[...document.querySelectorAll('.card:not([hidden])')];visible.forEach(c=>c.style.gridColumn='');if(innerWidth>1100){let r=visible.length%3;if(r===1)visible.at(-1).style.gridColumn='span 6';if(r===2)visible.slice(-2).forEach(c=>c.style.gridColumn='span 3');}
if(innerWidth>470&&innerWidth<=1100&&visible.length%2)visible.at(-1).style.gridColumn='1 / -1';
window.ScrollTrigger?.refresh();}
topics.addEventListener('click',e=>{const b=e.target.closest('button');if(b){active=b.dataset.topic;filter();}});search.addEventListener('input',filter);window.addEventListener('resize',filter);document.getElementById('reset').addEventListener('click',()=>{active='all';search.value='';filter();search.focus();});filter();
const motion=document.getElementById('motion');const preference=matchMedia('(prefers-reduced-motion: reduce)');window.previewsPaused=preference.matches;function motionLabel(){motion.textContent=window.previewsPaused?'▷ Play previews':'Ⅱ Pause previews';motion.setAttribute('aria-pressed',String(window.previewsPaused));}motionLabel();motion.addEventListener('click',()=>{window.previewsPaused=!window.previewsPaused;motionLabel();});
const menu=document.getElementById('simulation-menu'),viewer=document.getElementById('simulation-view'),frame=document.getElementById('simulation-frame'),back=document.getElementById('simulation-back');let focusBefore=null,scrollBefore=0;const title=document.title;
function syncViewer(){const sim=SIMS.find(s=>location.hash===viewerHref(s));if(sim){if(viewer.hidden){focusBefore=document.activeElement;scrollBefore=scrollY;}frame.title=sim.title;if(frame.getAttribute('src')!==sim.href)frame.src=sim.href;document.getElementById('simulation-direct').href=sim.href;menu.hidden=true;viewer.hidden=false;document.body.classList.add('viewing-simulation');document.title=sim.title+' — Biostatistics in motion';back.focus();}else if(!viewer.hidden){viewer.hidden=true;menu.hidden=false;frame.removeAttribute('src');document.body.classList.remove('viewing-simulation');document.title=title;requestAnimationFrame(()=>{window.scrollTo({top:scrollBefore,behavior:'instant'});focusBefore?.focus({preventScroll:true});window.ScrollTrigger?.refresh();});}}
window.addEventListener('hashchange',syncViewer);syncViewer();
const select=document.getElementById('sim-select');SIMS.forEach(s=>{const o=new Option(s.title,s.id);o.selected=s.id==='clt';select.add(o);});
function snippet(){const s=SIMS.find(s=>s.id===select.value);return `<iframe src="${s.href}"\n  title="${esc(s.title)}"\n  width="100%" height="640"\n  style="border:1px solid #ccc"\n  loading="lazy" allowfullscreen></iframe>`;}
function refresh(){document.getElementById('embed-code').textContent=snippet();}select.addEventListener('change',refresh);refresh();let toastTimer;
async function copy(text){const toast=document.getElementById('toast');try{await navigator.clipboard.writeText(text);toast.textContent='Copied to clipboard';}catch{toast.textContent='Copy unavailable. Select the text and copy it manually.';}toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),3000);}
document.getElementById('copy-embed').addEventListener('click',()=>copy(snippet()));document.getElementById('copy-cite').addEventListener('click',()=>copy('Teixeira-Pinto, A. Statistical simulations for teaching. https://atpinto.github.io/'));
if(window.gsap&&window.ScrollTrigger){gsap.registerPlugin(ScrollTrigger);const mm=gsap.matchMedia();mm.add('(prefers-reduced-motion: no-preference)',()=>{gsap.from('.hero h1',{y:12,opacity:.2,duration:.9,ease:'power2.out'});gsap.from('.teaching-intro',{opacity:.35,y:20,scrollTrigger:{trigger:'.teaching',start:'top 92%',end:'top 65%',scrub:true}});});mm.add('(min-width: 701px) and (prefers-reduced-motion: no-preference)',()=>{ScrollTrigger.create({trigger:'#topic-index',start:'top 28px',end:()=>'+='+Math.max(0,document.querySelector('.results').offsetHeight-document.getElementById('topic-index').offsetHeight),pin:true,pinSpacing:false,invalidateOnRefresh:true});});}
})();
