// Add simulations here. Each id must be unique; group matches a topic id.
  window.GROUPS = [
    { id: "nn", n: "01", title: "Neural networks", nav: "Networks" },
    { id: "bayes", n: "02", title: "Bayesian computation", nav: "Bayesian" },
    { id: "reg", n: "03", title: "Regression models", nav: "Regression" },
    { id: "trial", n: "04", title: "Trial design", nav: "Trials" },
    { id: "samp", n: "05", title: "Sampling distributions", nav: "Sampling" },
    { id: "prob", n: "06", title: "Probability", nav: "Probability" },
    { id: "infer", n: "07", title: "Hypothesis tests", nav: "Inference" },
    { id: "diag", n: "08", title: "Diagnostic tests", nav: "Diagnostics" },
    { id: "survival", n: "09", title: "Survival analysis", nav: "Survival" },
  ];
  window.SIMS = [
    { id: "km", group: "survival", href: "https://atpinto.github.io/KM/", title: "Kaplan–Meier, a step at a time", hook: "Follow 21 patients and build the survival curve one event at a time.", detail: "Step through patient follow-up, the risk set and the life table together. See how events lower the survival estimate, how censoring changes later risk sets, and how each conditional probability contributes to the Kaplan–Meier curve. Play automatically or move forward and backward one time point at a time." },
    { id: "nn", group: "nn", href: "https://atpinto.github.io/nn", title: "Backpropagation, one step at a time", hook: "Advance a single training pass phase by phase and see every formula with the numbers filled in.", detail: "A minimal two-neuron sigmoid network trained on one or two data points. Each of the six phases — two forward, loss, two backward, update — is advanced individually. Toggles for a second input, a second sample, SGD versus batch updating, and the learning rate." },
    { id: "mcmc", group: "bayes", href: "https://atpinto.github.io/MCMC/index.html", title: "Metropolis–Hastings, Gibbs and HMC side by side", hook: "Watch three samplers explore the same bivariate normal and see where each one struggles.", detail: "An animated dashboard showing the chain's path in the joint space alongside the two marginal distributions as they build up. Adjustable number of draws, animation speed, and HMC leapfrog steps and step size." },
    { id: "nlin", group: "reg", href: "https://atpinto.github.io/MultipleLinearRegression/nonlineareffects.html", title: "Non-linear effects in a linear model", hook: "Fit a curved BMI–blood pressure association without leaving the linear model framework.", detail: "Switch between polynomials, fractional polynomials, linear splines and restricted cubic splines; vary the degree, the powers and the number of knots; compare the fitted curves and R²." },
    { id: "corr", group: "reg", href: "https://atpinto.github.io/MultipleLinearRegression/mr_corr.html", title: "Correlated covariates", hook: "Turn up the correlation between two covariates and see what it does to their coefficients.", detail: "Set the sample size and the three pairwise correlations — between the two covariates, and between each covariate and the outcome — then inspect the fitted regression, the coefficient estimates and the residual plot as they change." },
    { id: "contbin", group: "reg", href: "https://atpinto.github.io/MultipleLinearRegression/cont_bin.html", title: "One continuous and one binary covariate", hook: "See why this model is just two parallel lines, one per level of the binary covariate.", detail: "Sliders for the correlation between the two covariates, the R², and the sample size, with the fitted lines redrawn as each changes." },
    { id: "dummy", group: "reg", href: "https://atpinto.github.io/MultipleLinearRegression/dummy.html", title: "Coding dummy variables", hook: "See how a categorical variable becomes a set of 0/1 columns, and what the reference level does.", detail: "An interactive demonstration of how dummy variables are coded from a categorical variable." },
    { id: "rand", group: "trial", href: "https://atpinto.github.io/rand/", title: "Randomisation from a table of digits", hook: "Enrol patients one at a time the way it was done on paper, then see how far the groups drift apart.", detail: "Pick a starting cell in a grid of random digits, apply a digit-to-allocation rule, and allocate under simple or blocked randomisation. Plots the running treatment−control imbalance, then re-runs the same design 2,000 times to show the distribution of the final imbalance. Includes teaching notes and discussion questions." },
    { id: "power", group: "trial", href: "https://atpinto.github.io/samplesize/", title: "Sample size and power calculator", hook: "Size a study for the outcome you actually have, and check the formula against a simulation.", detail: "Covers continuous, binary, odds ratio, hazard ratio, restricted mean survival time and count outcomes. Every scenario can be computed from the closed-form formula or by simulation, so the two can be compared directly; the simulation mode also allows for adjustment for a baseline covariate correlated with the outcome." },
    { id: "clt", group: "samp", href: "https://atpinto.github.io/CLT/", title: "The central limit theorem", hook: "Draw a population by hand, then watch the sampling distribution of the mean turn normal anyway.", detail: "Set a population distribution — normal, uniform, exponential, bimodal, or sketched directly on the plot — then draw repeated samples of size 5 to 100 and accumulate the sampling distribution of the mean or the median against a fitted normal curve." },
    { id: "galton", group: "samp", href: "https://atpinto.github.io/galton/", title: "The Galton board", hook: "Every ball takes nine independent coin flips on its way down, and the bell shape appears without anyone drawing it.", detail: "A physical simulation of a nine-row pin board. Release a single ball and follow its path, or open the hopper and let a stream run until the bins fill. The heights that build up are the binomial distribution one ball at a time." },
    { id: "monty", group: "prob", href: "https://atpinto.github.io/MontyHall/", title: "The Monty Hall problem", hook: "Play a few rounds on instinct, then run ten thousand and watch the two strategies settle on 1/3 and 2/3.", detail: "Pick a door, watch the host open a goat, then stay or switch. A running tally keeps the win rate of each strategy separately and plots both against the 1/3 and 2/3 lines as rounds accumulate. Batches of 100, 1,000 or 10,000 rounds can be simulated under always-stay, always-switch, or both at once." },
    { id: "ht", group: "infer", href: "https://atpinto.github.io/HT/", title: "The power of a hypothesis test", hook: "Shift the alternative and watch power fill in as the two sampling distributions pull apart.", detail: "A test of H₀: μ = 0 based on the sample mean. Draw samples under the null and under a chosen alternative, see the critical region, and compare the type I error with the power of the test." },
    { id: "roc", group: "diag", href: "https://atpinto.github.io/ROC/ROC_AUC.html", title: "Diagnostic test cutoff and the ROC curve", hook: "Move the cutoff, add cutoffs, and watch the ROC curve being generated.", detail: "A continuous diagnostic-test scale with two overlapping groups. Sensitivity, specificity and the false-positive rate update as the cutoff moves; added cutoffs become points on the ROC, and the curve is built in front of you." },
  ];
